# Generated by Django 5.0.6 on 2024-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheussopkeng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
